### ISSUE TITLE
Support new Claude 3 models

### ISSUE THREAD

**Issue by ryicoh** [tak-bro/aicommit2#30]
### Feature request

Support new Claude 3 models: Haiku, Sonnet, Opus.

`claude-2.1` is a legecy model.

https://www.anthropic.com/api

### Why?

New models has more inteligence and lower cost.

**Comment by tak-bro** [comment]
@ryicoh thanks for your interest. I updated the code to support the `claude3` model. It support from version `1.8.4`.
Please upgrade `aicommit2` and take a look at this [docs](https://github.com/tak-bro/aicommit2?tab=readme-ov-file#anthropic_model).

**Comment by ryicoh** [comment]
Thank you so much.

I've confirmed that the Haiku is set as the default now.

```bash
$ aicommit2 config get ANTHROPIC_MODEL
ANTHROPIC_MODEL=claude-3-haiku-20240307
```
