### ISSUE TITLE
Support for Codestral

### ISSUE THREAD

**Issue by bhodrolok** [tak-bro/aicommit2#48]
### Feature request

Thanks for making this tool! Been enjoying tinkering around with it.

I think aicommit2 can be further extended to support Mistral AI's new coding-focused genAI model, Codestral.

### Why?

[Codestral](https://mistral.ai/news/codestral/) is a 22 billion parameter model, which was released end of last month by Mistral AI, which is optimized for assisting developers. 
Cool thing about this model is that the API, available at codestral.mistral.ai, is **free** to use/consume until August 1.
Additionally it will give the user another option in terms of choosing a different model for selecting the generated commit message.

### Alternatives

I tried to implement the feature myself and managed to get it working, albeit in a _hacky_ way. 
Here is the repo with my changes: https://github.com/bhodrolok/aicommit2-codestral

The main thing I noticed is that the API key for using Codestral is **different** from the one used for Mistral AI's other models. 
Also there is no endpoint for [listing all available](https://docs.mistral.ai/api/#operation/listModels) Mistral AI models for the main Codestral domain (codestral.mistral.ai) and as such the regular Mistral AI domain (api.mistral.ai) has to be used (alongside the regular API key  `MISTRAL_KEY`).

I have been trying to refactor it such that it works in a single `MistralService` class but keep running into the `Invalid AI type` error.

I can open a PR so you can take a look at it!

### Additional context

- Link to Codestral docs: https://docs.mistral.ai/capabilities/code_generation/
- A Codestral API key can be obtained from [here](https://console.mistral.ai/codestral) 
- Currently only one Codestral model is available: `codestral-2405` (which `codestral-latest` points to).
- The API has a rate limit of 30 requests per minute and a daily limit of 2000 requests.

**Comment by tak-bro** [comment]
Thank you for your interest in my project and for leaving the issue.
I have reviewed your code. I’m not sure about the necessity of the `checkAvailableModels` function in `CodestralService`. If it is not strictly needed, it might be better to remove it. In that case, you could also remove the `apiKeyMistral` variable.

Alternatively, you could modify `MistralService` to decide whether to use Codestral or Mistral based on the configured model(`MISTRAL_MODEL`). For instance, if MISTRAL_MODEL is `codestral-2405`, it would use Codestral’s endpoint. I hope my response is clear.

If you don’t mind, could you please create a pull request with your changes?

**Comment by bhodrolok** [comment]
Thanks for looking into it! Yeah I did remove the `checkAvailableModels` function originally but thought it could potentially be helpful down the road if Mistral AI releases more Codestral models.

Yup I see what you mean and that is exactly what I was trying to refactor i.e. have `MistralService` determine what API calls to make based on the `MISTRAL_MODEL` value.
![image](https://github.com/tak-bro/aicommit2/assets/51386657/0a26a746-da31-43fb-848b-7d53c4c7ea5a)

The main problem I see is `[CODESTRAL_KEY] Invalid AI type`, even after defining it in the `utils\config.ts` and `services\ai\ai.service.ts` files.

Sure will make the Pull Request soon, thanks!

**Comment by louis-lemon** [comment]
By the way, if you encounter the "Invalid AI type" message, you need to add the corresponding AI KEY to `AIType` in `ai.service.ts`. If you want to add Codestral, you need to include the code as follows:
<img width="453" alt="image" src="https://github.com/tak-bro/aicommit2/assets/46361622/80a55ef7-d7d9-4106-a948-f8fc19d0daa2">

and then add your AI service in `AIRequestManager`
<img width="703" alt="image" src="https://github.com/tak-bro/aicommit2/assets/46361622/01b8fbbd-03ca-4d3a-9865-ed72407b84b4">

After making this modification, no error will occur if `CODESTRAL_KEY` is set

**Comment by tak-bro** [comment]
By the way, if you encounter the "Invalid AI type" message, you need to add the corresponding AI KEY to `AIType` in `ai.service.ts`. If you want to add Codestral, you need to include the code as follows:
<img width="453" alt="image" src="https://github.com/tak-bro/aicommit2/assets/46361622/80a55ef7-d7d9-4106-a948-f8fc19d0daa2">

and then add your AI service in `AIRequestManager`
<img width="703" alt="image" src="https://github.com/tak-bro/aicommit2/assets/46361622/01b8fbbd-03ca-4d3a-9865-ed72407b84b4">

After making this modification, no error will occur if `CODESTRAL_KEY` is set

**Comment by bhodrolok** [comment]
Yup I noticed that earlier too but looks like I was getting that error message as I messed up the switch cases with the new `CODESTRAL` `AIType` haha.
![image](https://github.com/tak-bro/aicommit2/assets/51386657/38a194b1-4802-4359-add4-3d4c6e0f85af)


I also went ahead and submitted a PR with the refactored version and it does seem to be working but like I said earlier it is not the best of solutions...
![image](https://github.com/tak-bro/aicommit2/assets/51386657/9583a173-4c25-4c94-bc36-230a2a1849e1)
