### ISSUE TITLE
Error when running `aicommit2 config set GEMINI_KEY=<your key>`

### ISSUE THREAD

**Issue by troublescope** [tak-bro/aicommit2#50]
### Bug description

When attempting to set the GEMINI_KEY using the command aicommit2 config set GEMINI_KEY=<your key>, an error is encountered.

### Steps to Reproduce:
1. Open terminal/command prompt.
2. Run the command: `aicommit2 config set GEMINI_KEY=<your key>`.

### Error Message:

```(node:14544) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)```

### aicommit2 version

v1.9.8

### Environment

```shell
System:
    OS: android
    CPU: Unknown
    Memory: 2.31 GB / 7.43 GB
  Binaries:
    Node: 22.2.0 - /data/data/com.termux/files/usr/bin/node
    npm: 10.7.0 - /data/data/com.termux/files/usr/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by tak-bro** [comment]
Thank you for sharing the issue. I will figure out the issue.

**Comment by tak-bro** [comment]
This error occurs in node 21 version or later.
For now, try older version of Node.js(v20). I think it will take some time to fix the root cause.
