### ISSUE TITLE
Multiline response parsing

### ISSUE THREAD

**Issue by claygorman** [tak-bro/aicommit2#56]
### Feature request

I think it would be helpful to handle newline output from the response.

### Why?

To get clearer more robust message structure.

### Additional context

I love the work done on this library by the way! good work. Currently my response for the commit message is a single line.

Notes:
* using `-c` to copy to clipboard
* using openai `gpt-4o` 
* using custom prompt: "Prepend fix: to the first line in lowercase. Avoid overly verbose descriptions or unnecessary details. Start with a short sentence in imperative form, no more than 50 characters long. Then leave an empty line and continue with a more detailed explanation. Write only one sentence for the first part, and two to five sentences at most for the detailed explanation. Use bullet points for multiple changes when possible."

My prompt should generate something like

```
fix: update Node.js version to 20.15.0 in Dockerfile

- Updated Node.js version from 20.13.1 to 20.15.0 in the Dockerfile.
- Ensures consistency and compatibility with the specified Node.js version
```

**Comment by tak-bro** [comment]
@claygorman Thanks for posting the feature request.
I agree with the need for that too.

Can I see one of the `gpt-4o` response?
You don't have to upload your diff content.
I just want to see the response from gpt.

You can log it below command.
`aicommit2 config set logging=true`.
After setting up, you can check it in the `~/.aicommit2_log` folder.

**Comment by claygorman** [comment]
hey sure no problem. Here is what I got when i cat out the top of the file `aic2_2024-07-08_15:41:07_4e2cff4233e264bb.log`

```
[OPEN AI Response]
fix: update panel spec and panels to return 10 instead of null- Updated panelSpecs function to return 'Error in panel spec 10' instead of 'Error in panel spec'.- Updated panels function to return 'panels: 10' instead of 'panels: null'.


[AICommit2 Prompt]
..........
```

when formatted by hand I fix it to look like this

```
fix: update panel spec and panels to return 10 instead of null

- Updated panelSpecs function to return 'Error in panel spec 10' instead of 'Error in panel spec'.
- Updated panels function to return 'panels: 10' instead of 'panels: null'.
```

**Comment by tak-bro** [comment]
@claygorman I just published version v1.11.0. It can support multi-line now!
I touched the prompt in a big way by referring to your prompt. Please try.
![demo_body_min](https://github.com/tak-bro/aicommit2/blob/main/img/demo_body_min.gif?raw=true)

**Comment by claygorman** [comment]
hey there! I appreciate your looking into this. I do notice the multiline output is clearer now. However it seems its ignoring my prompt. I believe its due to my prompt being appended to the default prompt. I assumed that if i specify a prompt that it overrides the built in prompt. Is this not the case?

thanks!

**Comment by tak-bro** [comment]
As you can see, under the [AICcommit2prompt] section, 1 to 8 are default. Your prompt is being added as extra.
Sooner or later, I think it would be better to add an option to `overwritePrompt` the prompt itself.

**Comment by claygorman** [comment]
yeah I do see my prompt being appended to the bottom, but the side effect of that is that it has no effect really on the output because all of the previous prompt information basically overwriting my prompt information. I do realize this is a separate issue than my original issue which I believe is resolved so I can close this for now, but I do believe that I am not able to extract the same result that I was before with the same prompt almost which leads me to feel like it’s a regression of previously working behavior.

**Comment by tak-bro** [comment]
@claygorman Okay..  I will support the custom prompt template option. Please wait a little bit
