### ISSUE TITLE
Leading blank space in `prepare-commit-msg` hook

### ISSUE THREAD

**Issue by noamsto** [tak-bro/aicommit2#79]
### Bug description

I've installed the git hook and ran it, there is a blank line after the comment header and there shouldn't be any.
It other hooks to fail (for example using alongside https://github.com/ljnsn/cz-conventional-gitmoji)
![image](https://github.com/user-attachments/assets/31ceea1b-3415-45e3-9766-0c86cc3e3bc4)

![image](https://github.com/user-attachments/assets/bbc72ed5-e3e0-4eb5-85de-c0814dfc4d0b)
If I manually remove the leading new line the later hook works. 

### aicommit2 version

v10.2.4

### Environment

```shell
System:
    OS: Linux 6.10 NixOS 24.11 (Vicuna) 24.11 (Vicuna)
    CPU: (16) x64 AMD Ryzen 7 PRO 8840HS w/ Radeon 780M Graphics
    Memory: 51.39 GB / 58.51 GB
    Container: Yes
    Shell: 5.9 - /run/current-system/sw/bin/zsh
  Binaries:
    Node: 20.11.1 - /nix/store/wcg03hp9av1pgr3mj5m3dbanmz8jqq69-nodejs-slim-20.11.1/bin/node
    npm: 10.2.4 - /nix/store/frchj7ynjnj5rwbhhdkwig25lz41y854-nodejs-20.11.1/bin/npm
```

### Can you contribute a fix?

- [X] I’m interested in opening a pull request for this issue.

**Comment by tak-bro** [comment]
Thank you! Your code has been applied. Please use version v2.1.1.
