### ISSUE TITLE
maxContentLength size of -1 exceeded

### ISSUE THREAD

**Issue by hsu1943** [tak-bro/aicommit2#85]
### Bug description

When I make minor code changes, the generated commit message is perfect. However, if I modify many files at once and then run aicommit2, I encounter an error message: "✘ [DeepSeek] maxContentLength size of -1 exceeded". I am using DeepSeek and have not added any special configurations.

My configuration:

```
locale=zh

[DEEPSEEK]
key=sk-***
model=deepseek-chat
temperature=1
includeBody=true
```

![D08F5020-2A60-41e9-920E-B8255A2191BF](https://github.com/user-attachments/assets/d2c0367a-adea-4b66-97f4-8e9cc074cfdf)

### aicommit2 version

2.1.2

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 1.54 GB / 15.73 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.9.0 - C:\Program Files\nodejs\pnpm.CMD
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by tak-bro** [comment]
Thank you for raising the issue. It seems that when passing a large number of tokens, an error occurs in Deepseek. I'll look into it.

**Comment by hsu1943** [comment]
After upgrading to version 2.1.5 and setting maxTokens to 4096, it works fine.
